name: Lidar-Test-CI

on:
  push:
    paths:
      - 'src/ros/lidar/**'
  pull_request:
    paths:
      - 'src/ros/lidar/**'
  workflow_dispatch:

jobs:
  build:
    name: "Build [Lidar] Test (No ROS)"
    runs-on: ubuntu-latest
    steps:
      - run: echo '::echo::on'

      - name: "Get PCL"
        run: |
          sudo apt-get update && sudo apt-get install libpcl-dev

      - name: "Checkout"
        uses: actions/checkout@main
        with:
          submodules: recursive

      - name: "Build/Install"
        run: |
          pushd src/ros/lidar
          cmake . -B ./cmake-build -DTEST_NOROS=ON
          cmake --build ./cmake-build --target install --config Release --parallel $(nproc)
          popd

      - name: "Inspect Insall"
        run: |
          cd ./src/ros/lidar/install
          ls -l -R

      - name: "Upload Build Results"
        uses: actions/upload-artifact@main
        with:
          name: ci-build
          path: |
            ./src/ros/lidar/install
            ./src/ros/lidar/cmake-build
